name: SolarHub
version: '${version}'

main: dev.eychro.solarHub.SolarHub
api-version: '26.3'
load: POSTWORLD

authors: [ eychro ]

commands:
  solarhub:
    description: Comando principal de administración de SolarHub.
    usage: "§cUso correcto: /solarhub <help|reload>"
    aliases: [sh]

  discord:
    description: Muestra el enlace de Discord.
    usage: /<command>
    aliases: [dc]
    permission: Solar.Discord

  website:
    description: Muestra el enlace del sitio web.
    usage: /<command>
    permission: Solar.Website

  spawn:
    description: Teletransporta al jugador al spawn.
    usage: /<command>
    aliases: [hub]
    permission: Solar.Spawn

  buildmode:
    description: Activa o desactiva el modo de construcción.
    usage: /<command>
    permission: Solar.BuildMode

  setspawn:
    description: Establece la ubicación del spawn.
    usage: /<command>
    permission: Solar.SetSpawn

  fly:
    description: Vuela por el spawn
    usage: /<command>
    permission: Solar.Fly
    
  vanish:
    description: Hazte invisible para todos
    usage: /<command>
    permission: Solar.Vanish

  servers:
    description: Abre el menú selector de servidores.
    usage: /<command>
    aliases: [selector]
    permission: Solar.Menu.Servers

  cosmetics:
    description: Abre el menú de cosméticos del lobby.
    usage: /<command>
    aliases: [cosmeticos]
    permission: Solar.Menu.Cosmetics

  profile:
    description: Abre tu perfil de jugador.
    usage: /<command>
    aliases: [perfil]
    permission: Solar.Menu.Profile

  setparkourstart:
    description: Incio del parkour
    usage: /<command>
    aliases: [sps]
    permission: Solar.Admin.Parkour

  setparkourcheckpoint:
    description: Agrega checkpoint
    aliases: [spc]
    permission: Solar.Admin.Parkour

permissions:
  Solar.CooldownBypass:
    description: Permite ignorar todos los cooldowns de comandos, doble salto y launchpad.
    default: op
  Solar.Discord:
    default: op
  Solar.Website:
    default: op
  Solar.Spawn:
    default: op
  Solar.DoubleJump:
    default: op
  Solar.LaunchPad:
    default: op
  Solar.JoinMessage:
    default: op
  Solar.BuildMode:
    default: op
  Solar.SetSpawn:
    default: op
  Solar.Admin:
    default: op
  Solar.Fly:
    default: op
  Solar.Vanish:
    default: op
  Solar.Admin.Parkour:
    default: op
  Solar.Menu.Servers:
    default: true
  Solar.Menu.Cosmetics:
    default: true
  Solar.Menu.Profile:
    default: true
  Solar.Hotbar:
    default: true